// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAPIKeyByParentID = `-- name: DeleteAPIKeyByParentID :exec
DELETE FROM api_keys
WHERE parent_id = $1
`

func (q *Queries) DeleteAPIKeyByParentID(ctx context.Context, parentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIKeyByParentID, parentID)
	return err
}

const getAPIKeyByParentID = `-- name: GetAPIKeyByParentID :one
SELECT id, parent_id, encrypted_key, created_at, updated_at FROM api_keys
WHERE parent_id = $1
LIMIT 1
`

func (q *Queries) GetAPIKeyByParentID(ctx context.Context, parentID pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByParentID, parentID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.EncryptedKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAPIKey = `-- name: UpsertAPIKey :one
INSERT INTO api_keys (parent_id, encrypted_key)
VALUES ($1, $2)
ON CONFLICT (parent_id)
DO UPDATE SET encrypted_key = EXCLUDED.encrypted_key,
              updated_at = NOW()
RETURNING id, parent_id, encrypted_key, created_at, updated_at
`

type UpsertAPIKeyParams struct {
	ParentID     pgtype.UUID `json:"parent_id"`
	EncryptedKey []byte      `json:"encrypted_key"`
}

func (q *Queries) UpsertAPIKey(ctx context.Context, arg UpsertAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, upsertAPIKey, arg.ParentID, arg.EncryptedKey)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.EncryptedKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
