// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: challenges.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChallenge = `-- name: CreateChallenge :one

INSERT INTO challenges (parent_id, created_by_role, title, description, cover_emoji, created_by_student_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, parent_id, created_by_role, title, description, cover_emoji, created_at, published, created_by_student_id
`

type CreateChallengeParams struct {
	ParentID           pgtype.UUID `json:"parent_id"`
	CreatedByRole      string      `json:"created_by_role"`
	Title              string      `json:"title"`
	Description        string      `json:"description"`
	CoverEmoji         string      `json:"cover_emoji"`
	CreatedByStudentID pgtype.UUID `json:"created_by_student_id"`
}

// backend/db/queries/challenges.sql
func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, createChallenge,
		arg.ParentID,
		arg.CreatedByRole,
		arg.Title,
		arg.Description,
		arg.CoverEmoji,
		arg.CreatedByStudentID,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.CreatedByRole,
		&i.Title,
		&i.Description,
		&i.CoverEmoji,
		&i.CreatedAt,
		&i.Published,
		&i.CreatedByStudentID,
	)
	return i, err
}

const createChallengeExercise = `-- name: CreateChallengeExercise :one
INSERT INTO challenge_exercises (challenge_id, title, description, system_prompt, display_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, challenge_id, title, description, system_prompt, display_order, created_at
`

type CreateChallengeExerciseParams struct {
	ChallengeID  pgtype.UUID `json:"challenge_id"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	SystemPrompt string      `json:"system_prompt"`
	DisplayOrder int32       `json:"display_order"`
}

func (q *Queries) CreateChallengeExercise(ctx context.Context, arg CreateChallengeExerciseParams) (ChallengeExercise, error) {
	row := q.db.QueryRow(ctx, createChallengeExercise,
		arg.ChallengeID,
		arg.Title,
		arg.Description,
		arg.SystemPrompt,
		arg.DisplayOrder,
	)
	var i ChallengeExercise
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.Title,
		&i.Description,
		&i.SystemPrompt,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChallenge = `-- name: DeleteChallenge :exec
DELETE FROM challenges WHERE id = $1 AND parent_id = $2
`

type DeleteChallengeParams struct {
	ID       pgtype.UUID `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) DeleteChallenge(ctx context.Context, arg DeleteChallengeParams) error {
	_, err := q.db.Exec(ctx, deleteChallenge, arg.ID, arg.ParentID)
	return err
}

const getChallengeByID = `-- name: GetChallengeByID :one
SELECT id, parent_id, created_by_role, title, description, cover_emoji, created_at, published, created_by_student_id
FROM challenges
WHERE id = $1
`

func (q *Queries) GetChallengeByID(ctx context.Context, id pgtype.UUID) (Challenge, error) {
	row := q.db.QueryRow(ctx, getChallengeByID, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.CreatedByRole,
		&i.Title,
		&i.Description,
		&i.CoverEmoji,
		&i.CreatedAt,
		&i.Published,
		&i.CreatedByStudentID,
	)
	return i, err
}

const getChallengeExerciseByID = `-- name: GetChallengeExerciseByID :one
SELECT id, challenge_id, title, description, system_prompt, display_order, created_at
FROM challenge_exercises
WHERE id = $1
`

func (q *Queries) GetChallengeExerciseByID(ctx context.Context, id pgtype.UUID) (ChallengeExercise, error) {
	row := q.db.QueryRow(ctx, getChallengeExerciseByID, id)
	var i ChallengeExercise
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.Title,
		&i.Description,
		&i.SystemPrompt,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listChallengeExercisesByChallengeID = `-- name: ListChallengeExercisesByChallengeID :many
SELECT id, challenge_id, title, description, system_prompt, display_order, created_at
FROM challenge_exercises
WHERE challenge_id = $1
ORDER BY display_order
`

func (q *Queries) ListChallengeExercisesByChallengeID(ctx context.Context, challengeID pgtype.UUID) ([]ChallengeExercise, error) {
	rows, err := q.db.Query(ctx, listChallengeExercisesByChallengeID, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChallengeExercise
	for rows.Next() {
		var i ChallengeExercise
		if err := rows.Scan(
			&i.ID,
			&i.ChallengeID,
			&i.Title,
			&i.Description,
			&i.SystemPrompt,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChallengeExercisesWithProgress = `-- name: ListChallengeExercisesWithProgress :many
SELECT DISTINCT ON (ce.display_order, ce.id)
    ce.id,
    ce.title,
    ce.description,
    ce.display_order,
    s.id AS session_id,
    s.score AS score
FROM challenge_exercises ce
LEFT JOIN sessions s ON s.challenge_exercise_id = ce.id
    AND s.student_id = $2
    AND s.ended_at IS NOT NULL
WHERE ce.challenge_id = $1
ORDER BY ce.display_order, ce.id, s.score DESC NULLS LAST
`

type ListChallengeExercisesWithProgressParams struct {
	ChallengeID pgtype.UUID `json:"challenge_id"`
	StudentID   pgtype.UUID `json:"student_id"`
}

type ListChallengeExercisesWithProgressRow struct {
	ID           pgtype.UUID `json:"id"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	DisplayOrder int32       `json:"display_order"`
	SessionID    pgtype.UUID `json:"session_id"`
	Score        pgtype.Int4 `json:"score"`
}

func (q *Queries) ListChallengeExercisesWithProgress(ctx context.Context, arg ListChallengeExercisesWithProgressParams) ([]ListChallengeExercisesWithProgressRow, error) {
	rows, err := q.db.Query(ctx, listChallengeExercisesWithProgress, arg.ChallengeID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChallengeExercisesWithProgressRow
	for rows.Next() {
		var i ListChallengeExercisesWithProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DisplayOrder,
			&i.SessionID,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChallengesByParentID = `-- name: ListChallengesByParentID :many
SELECT c.id, c.parent_id, c.created_by_role, c.title, c.description, c.cover_emoji, c.created_at, c.published,
    COALESCE(st.name, '')::text AS creator_name
FROM challenges c
LEFT JOIN students st ON st.id = c.created_by_student_id
WHERE c.parent_id = $1
ORDER BY c.created_at DESC
`

type ListChallengesByParentIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	ParentID      pgtype.UUID        `json:"parent_id"`
	CreatedByRole string             `json:"created_by_role"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	CoverEmoji    string             `json:"cover_emoji"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Published     bool               `json:"published"`
	CreatorName   string             `json:"creator_name"`
}

func (q *Queries) ListChallengesByParentID(ctx context.Context, parentID pgtype.UUID) ([]ListChallengesByParentIDRow, error) {
	rows, err := q.db.Query(ctx, listChallengesByParentID, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChallengesByParentIDRow
	for rows.Next() {
		var i ListChallengesByParentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.CreatedByRole,
			&i.Title,
			&i.Description,
			&i.CoverEmoji,
			&i.CreatedAt,
			&i.Published,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedChallengesByParentID = `-- name: ListPublishedChallengesByParentID :many
SELECT c.id, c.parent_id, c.created_by_role, c.title, c.description, c.cover_emoji, c.created_at, c.published,
    COALESCE(st.name, '')::text AS creator_name
FROM challenges c
LEFT JOIN students st ON st.id = c.created_by_student_id
WHERE c.parent_id = $1 AND c.published = true
ORDER BY c.created_at DESC
`

type ListPublishedChallengesByParentIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	ParentID      pgtype.UUID        `json:"parent_id"`
	CreatedByRole string             `json:"created_by_role"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	CoverEmoji    string             `json:"cover_emoji"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Published     bool               `json:"published"`
	CreatorName   string             `json:"creator_name"`
}

func (q *Queries) ListPublishedChallengesByParentID(ctx context.Context, parentID pgtype.UUID) ([]ListPublishedChallengesByParentIDRow, error) {
	rows, err := q.db.Query(ctx, listPublishedChallengesByParentID, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedChallengesByParentIDRow
	for rows.Next() {
		var i ListPublishedChallengesByParentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.CreatedByRole,
			&i.Title,
			&i.Description,
			&i.CoverEmoji,
			&i.CreatedAt,
			&i.Published,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishChallenge = `-- name: PublishChallenge :one
UPDATE challenges
SET title = $1, published = true
WHERE id = $2 AND parent_id = $3
RETURNING id, parent_id, created_by_role, title, description, cover_emoji, created_at, published, created_by_student_id
`

type PublishChallengeParams struct {
	Title    string      `json:"title"`
	ID       pgtype.UUID `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) PublishChallenge(ctx context.Context, arg PublishChallengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, publishChallenge, arg.Title, arg.ID, arg.ParentID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.CreatedByRole,
		&i.Title,
		&i.Description,
		&i.CoverEmoji,
		&i.CreatedAt,
		&i.Published,
		&i.CreatedByStudentID,
	)
	return i, err
}
