// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, topic_id, title, description, difficulty_order, system_prompt FROM exercises WHERE id = $1
`

type GetExerciseByIDRow struct {
	ID              pgtype.UUID `json:"id"`
	TopicID         pgtype.UUID `json:"topic_id"`
	Title           string      `json:"title"`
	Description     string      `json:"description"`
	DifficultyOrder int32       `json:"difficulty_order"`
	SystemPrompt    string      `json:"system_prompt"`
}

func (q *Queries) GetExerciseByID(ctx context.Context, id pgtype.UUID) (GetExerciseByIDRow, error) {
	row := q.db.QueryRow(ctx, getExerciseByID, id)
	var i GetExerciseByIDRow
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Title,
		&i.Description,
		&i.DifficultyOrder,
		&i.SystemPrompt,
	)
	return i, err
}

const listExercisesByTopicID = `-- name: ListExercisesByTopicID :many
SELECT id, topic_id, title, description, difficulty_order FROM exercises WHERE topic_id = $1 ORDER BY difficulty_order
`

type ListExercisesByTopicIDRow struct {
	ID              pgtype.UUID `json:"id"`
	TopicID         pgtype.UUID `json:"topic_id"`
	Title           string      `json:"title"`
	Description     string      `json:"description"`
	DifficultyOrder int32       `json:"difficulty_order"`
}

func (q *Queries) ListExercisesByTopicID(ctx context.Context, topicID pgtype.UUID) ([]ListExercisesByTopicIDRow, error) {
	rows, err := q.db.Query(ctx, listExercisesByTopicID, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExercisesByTopicIDRow
	for rows.Next() {
		var i ListExercisesByTopicIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Title,
			&i.Description,
			&i.DifficultyOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
