// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: family.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFamilySettings = `-- name: GetFamilySettings :one
SELECT id, code_hash, device_epoch, updated_at FROM family_settings WHERE id = 1
`

func (q *Queries) GetFamilySettings(ctx context.Context) (FamilySetting, error) {
	row := q.db.QueryRow(ctx, getFamilySettings)
	var i FamilySetting
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.DeviceEpoch,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllStudents = `-- name: ListAllStudents :many
SELECT id, name FROM students ORDER BY created_at
`

type ListAllStudentsRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListAllStudents(ctx context.Context) ([]ListAllStudentsRow, error) {
	rows, err := q.db.Query(ctx, listAllStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllStudentsRow
	for rows.Next() {
		var i ListAllStudentsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParents = `-- name: ListParents :many
SELECT id, email FROM parents ORDER BY created_at
`

type ListParentsRow struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) ListParents(ctx context.Context) ([]ListParentsRow, error) {
	rows, err := q.db.Query(ctx, listParents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParentsRow
	for rows.Next() {
		var i ListParentsRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFamilyCode = `-- name: UpsertFamilyCode :one
INSERT INTO family_settings (id, code_hash)
VALUES (1, $1)
ON CONFLICT (id) DO UPDATE SET
    code_hash = $1,
    device_epoch = family_settings.device_epoch + 1,
    updated_at = NOW()
RETURNING id, code_hash, device_epoch, updated_at
`

func (q *Queries) UpsertFamilyCode(ctx context.Context, codeHash string) (FamilySetting, error) {
	row := q.db.QueryRow(ctx, upsertFamilyCode, codeHash)
	var i FamilySetting
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.DeviceEpoch,
		&i.UpdatedAt,
	)
	return i, err
}
