// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID           pgtype.UUID        `json:"id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	EncryptedKey []byte             `json:"encrypted_key"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Parent struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	GdprConsentAt pgtype.Timestamptz `json:"gdpr_consent_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PinAttempt struct {
	StudentID     pgtype.UUID        `json:"student_id"`
	Attempts      int32              `json:"attempts"`
	LockedUntil   pgtype.Timestamptz `json:"locked_until"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
}

type Student struct {
	ID              pgtype.UUID        `json:"id"`
	ParentID        pgtype.UUID        `json:"parent_id"`
	Name            string             `json:"name"`
	PinHash         pgtype.Text        `json:"pin_hash"`
	InviteCode      pgtype.Text        `json:"invite_code"`
	InviteExpiresAt pgtype.Timestamptz `json:"invite_expires_at"`
	ActivatedAt     pgtype.Timestamptz `json:"activated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
