// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parents.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParent = `-- name: CreateParent :one
INSERT INTO parents (email, password_hash, gdpr_consent_at)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, gdpr_consent_at, created_at
`

type CreateParentParams struct {
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	GdprConsentAt pgtype.Timestamptz `json:"gdpr_consent_at"`
}

func (q *Queries) CreateParent(ctx context.Context, arg CreateParentParams) (Parent, error) {
	row := q.db.QueryRow(ctx, createParent, arg.Email, arg.PasswordHash, arg.GdprConsentAt)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GdprConsentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getParentByEmail = `-- name: GetParentByEmail :one
SELECT id, email, password_hash, gdpr_consent_at, created_at FROM parents
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetParentByEmail(ctx context.Context, email string) (Parent, error) {
	row := q.db.QueryRow(ctx, getParentByEmail, email)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GdprConsentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getParentByID = `-- name: GetParentByID :one
SELECT id, email, password_hash, gdpr_consent_at, created_at FROM parents
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetParentByID(ctx context.Context, id pgtype.UUID) (Parent, error) {
	row := q.db.QueryRow(ctx, getParentByID, id)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GdprConsentAt,
		&i.CreatedAt,
	)
	return i, err
}
