// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: progress.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStudentProgressBySubject = `-- name: GetStudentProgressBySubject :many
SELECT s.id, s.name, s.slug,
  COUNT(DISTINCT se.id)::int AS total_sessions,
  COALESCE(ROUND(AVG(se.score)::numeric, 1), 0)::float8 AS avg_score,
  COUNT(DISTINCT se.exercise_id)::int AS unique_exercises
FROM subjects s
LEFT JOIN topics t ON t.subject_id = s.id
LEFT JOIN exercises e ON e.topic_id = t.id
LEFT JOIN sessions se ON se.exercise_id = e.id AND se.student_id = $1 AND se.ended_at IS NOT NULL AND se.score IS NOT NULL
GROUP BY s.id, s.name, s.slug, s.display_order
ORDER BY s.display_order
`

type GetStudentProgressBySubjectRow struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	Slug            string      `json:"slug"`
	TotalSessions   int32       `json:"total_sessions"`
	AvgScore        float64     `json:"avg_score"`
	UniqueExercises int32       `json:"unique_exercises"`
}

func (q *Queries) GetStudentProgressBySubject(ctx context.Context, studentID pgtype.UUID) ([]GetStudentProgressBySubjectRow, error) {
	rows, err := q.db.Query(ctx, getStudentProgressBySubject, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentProgressBySubjectRow
	for rows.Next() {
		var i GetStudentProgressBySubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.TotalSessions,
			&i.AvgScore,
			&i.UniqueExercises,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentProgressByTopic = `-- name: GetStudentProgressByTopic :many
SELECT t.id, t.name, t.slug,
  COUNT(DISTINCT se.id)::int AS total_sessions,
  COALESCE(ROUND(AVG(se.score)::numeric, 1), 0)::float8 AS avg_score,
  COUNT(DISTINCT se.exercise_id)::int AS unique_exercises
FROM topics t
LEFT JOIN exercises e ON e.topic_id = t.id
LEFT JOIN sessions se ON se.exercise_id = e.id AND se.student_id = $1 AND se.ended_at IS NOT NULL AND se.score IS NOT NULL
WHERE t.subject_id = $2
GROUP BY t.id, t.name, t.slug, t.display_order
ORDER BY t.display_order
`

type GetStudentProgressByTopicParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	SubjectID pgtype.UUID `json:"subject_id"`
}

type GetStudentProgressByTopicRow struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	Slug            string      `json:"slug"`
	TotalSessions   int32       `json:"total_sessions"`
	AvgScore        float64     `json:"avg_score"`
	UniqueExercises int32       `json:"unique_exercises"`
}

func (q *Queries) GetStudentProgressByTopic(ctx context.Context, arg GetStudentProgressByTopicParams) ([]GetStudentProgressByTopicRow, error) {
	rows, err := q.db.Query(ctx, getStudentProgressByTopic, arg.StudentID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentProgressByTopicRow
	for rows.Next() {
		var i GetStudentProgressByTopicRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.TotalSessions,
			&i.AvgScore,
			&i.UniqueExercises,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedSessions = `-- name: ListCompletedSessions :many
SELECT se.id, se.score, se.started_at, se.ended_at,
  e.title AS exercise_title,
  t.name AS topic_name,
  s.name AS subject_name
FROM sessions se
JOIN exercises e ON e.id = se.exercise_id
JOIN topics t ON t.id = e.topic_id
JOIN subjects s ON s.id = t.subject_id
WHERE se.student_id = $1 AND se.ended_at IS NOT NULL AND se.score IS NOT NULL
ORDER BY se.ended_at DESC
`

type ListCompletedSessionsRow struct {
	ID            pgtype.UUID        `json:"id"`
	Score         pgtype.Int4        `json:"score"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	EndedAt       pgtype.Timestamptz `json:"ended_at"`
	ExerciseTitle string             `json:"exercise_title"`
	TopicName     string             `json:"topic_name"`
	SubjectName   string             `json:"subject_name"`
}

func (q *Queries) ListCompletedSessions(ctx context.Context, studentID pgtype.UUID) ([]ListCompletedSessionsRow, error) {
	rows, err := q.db.Query(ctx, listCompletedSessions, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedSessionsRow
	for rows.Next() {
		var i ListCompletedSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Score,
			&i.StartedAt,
			&i.EndedAt,
			&i.ExerciseTitle,
			&i.TopicName,
			&i.SubjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
