// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_schedule.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReviewSchedule = `-- name: GetReviewSchedule :one
SELECT id, student_id, exercise_id, ease_factor, interval_days, repetition_count, next_review, last_reviewed_at, created_at FROM review_schedule WHERE student_id = $1 AND exercise_id = $2
`

type GetReviewScheduleParams struct {
	StudentID  pgtype.UUID `json:"student_id"`
	ExerciseID pgtype.UUID `json:"exercise_id"`
}

func (q *Queries) GetReviewSchedule(ctx context.Context, arg GetReviewScheduleParams) (ReviewSchedule, error) {
	row := q.db.QueryRow(ctx, getReviewSchedule, arg.StudentID, arg.ExerciseID)
	var i ReviewSchedule
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ExerciseID,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.RepetitionCount,
		&i.NextReview,
		&i.LastReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDueReviews = `-- name: ListDueReviews :many
SELECT
    rs.id,
    rs.exercise_id,
    rs.next_review,
    rs.interval_days,
    rs.ease_factor,
    e.title AS exercise_title,
    t.name AS topic_name,
    t.slug AS topic_slug,
    s.name AS subject_name,
    s.slug AS subject_slug
FROM review_schedule rs
JOIN exercises e ON e.id = rs.exercise_id
JOIN topics t ON t.id = e.topic_id
JOIN subjects s ON s.id = t.subject_id
WHERE rs.student_id = $1
  AND rs.next_review <= NOW()
ORDER BY rs.next_review ASC
`

type ListDueReviewsRow struct {
	ID            pgtype.UUID        `json:"id"`
	ExerciseID    pgtype.UUID        `json:"exercise_id"`
	NextReview    pgtype.Timestamptz `json:"next_review"`
	IntervalDays  int32              `json:"interval_days"`
	EaseFactor    float32            `json:"ease_factor"`
	ExerciseTitle string             `json:"exercise_title"`
	TopicName     string             `json:"topic_name"`
	TopicSlug     string             `json:"topic_slug"`
	SubjectName   string             `json:"subject_name"`
	SubjectSlug   string             `json:"subject_slug"`
}

func (q *Queries) ListDueReviews(ctx context.Context, studentID pgtype.UUID) ([]ListDueReviewsRow, error) {
	rows, err := q.db.Query(ctx, listDueReviews, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueReviewsRow
	for rows.Next() {
		var i ListDueReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.NextReview,
			&i.IntervalDays,
			&i.EaseFactor,
			&i.ExerciseTitle,
			&i.TopicName,
			&i.TopicSlug,
			&i.SubjectName,
			&i.SubjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReviewSchedule = `-- name: UpsertReviewSchedule :one
INSERT INTO review_schedule (student_id, exercise_id, ease_factor, interval_days, repetition_count, next_review, last_reviewed_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (student_id, exercise_id)
DO UPDATE SET
    ease_factor = $3,
    interval_days = $4,
    repetition_count = $5,
    next_review = $6,
    last_reviewed_at = NOW()
RETURNING id, student_id, exercise_id, ease_factor, interval_days, repetition_count, next_review, last_reviewed_at, created_at
`

type UpsertReviewScheduleParams struct {
	StudentID       pgtype.UUID        `json:"student_id"`
	ExerciseID      pgtype.UUID        `json:"exercise_id"`
	EaseFactor      float32            `json:"ease_factor"`
	IntervalDays    int32              `json:"interval_days"`
	RepetitionCount int32              `json:"repetition_count"`
	NextReview      pgtype.Timestamptz `json:"next_review"`
}

func (q *Queries) UpsertReviewSchedule(ctx context.Context, arg UpsertReviewScheduleParams) (ReviewSchedule, error) {
	row := q.db.QueryRow(ctx, upsertReviewSchedule,
		arg.StudentID,
		arg.ExerciseID,
		arg.EaseFactor,
		arg.IntervalDays,
		arg.RepetitionCount,
		arg.NextReview,
	)
	var i ReviewSchedule
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ExerciseID,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.RepetitionCount,
		&i.NextReview,
		&i.LastReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}
