// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (student_id, exercise_id) VALUES ($1, $2) RETURNING id, student_id, exercise_id, score, summary, started_at, ended_at
`

type CreateSessionParams struct {
	StudentID  pgtype.UUID `json:"student_id"`
	ExerciseID pgtype.UUID `json:"exercise_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.StudentID, arg.ExerciseID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ExerciseID,
		&i.Score,
		&i.Summary,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const endSession = `-- name: EndSession :one
UPDATE sessions SET ended_at = NOW(), score = $2, summary = $3 WHERE id = $1 AND ended_at IS NULL RETURNING id, student_id, exercise_id, score, summary, started_at, ended_at
`

type EndSessionParams struct {
	ID      pgtype.UUID `json:"id"`
	Score   pgtype.Int4 `json:"score"`
	Summary pgtype.Text `json:"summary"`
}

func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, endSession, arg.ID, arg.Score, arg.Summary)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ExerciseID,
		&i.Score,
		&i.Summary,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, student_id, exercise_id, score, summary, started_at, ended_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ExerciseID,
		&i.Score,
		&i.Summary,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listSessionsByStudentID = `-- name: ListSessionsByStudentID :many
SELECT id, student_id, exercise_id, score, summary, started_at, ended_at FROM sessions WHERE student_id = $1 ORDER BY started_at DESC
`

func (q *Queries) ListSessionsByStudentID(ctx context.Context, studentID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByStudentID, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.ExerciseID,
			&i.Score,
			&i.Summary,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
