// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateStudent = `-- name: ActivateStudent :one
UPDATE students
SET pin_hash = $2,
    activated_at = NOW(),
    invite_code = NULL,
    invite_expires_at = NULL
WHERE invite_code = $1
  AND activated_at IS NULL
  AND invite_expires_at > NOW()
RETURNING id, parent_id, name, pin_hash, invite_code, invite_expires_at, activated_at, created_at
`

type ActivateStudentParams struct {
	InviteCode pgtype.Text `json:"invite_code"`
	PinHash    pgtype.Text `json:"pin_hash"`
}

func (q *Queries) ActivateStudent(ctx context.Context, arg ActivateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, activateStudent, arg.InviteCode, arg.PinHash)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.PinHash,
		&i.InviteCode,
		&i.InviteExpiresAt,
		&i.ActivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (parent_id, name, invite_code, invite_expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, parent_id, name, pin_hash, invite_code, invite_expires_at, activated_at, created_at
`

type CreateStudentParams struct {
	ParentID        pgtype.UUID        `json:"parent_id"`
	Name            string             `json:"name"`
	InviteCode      pgtype.Text        `json:"invite_code"`
	InviteExpiresAt pgtype.Timestamptz `json:"invite_expires_at"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.ParentID,
		arg.Name,
		arg.InviteCode,
		arg.InviteExpiresAt,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.PinHash,
		&i.InviteCode,
		&i.InviteExpiresAt,
		&i.ActivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, parent_id, name, pin_hash, invite_code, invite_expires_at, activated_at, created_at FROM students
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetStudentByID(ctx context.Context, id pgtype.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.PinHash,
		&i.InviteCode,
		&i.InviteExpiresAt,
		&i.ActivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentByNameAndParent = `-- name: GetStudentByNameAndParent :one
SELECT id, parent_id, name, pin_hash, invite_code, invite_expires_at, activated_at, created_at FROM students
WHERE name = $1
  AND parent_id = $2
LIMIT 1
`

type GetStudentByNameAndParentParams struct {
	Name     string      `json:"name"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) GetStudentByNameAndParent(ctx context.Context, arg GetStudentByNameAndParentParams) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByNameAndParent, arg.Name, arg.ParentID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.PinHash,
		&i.InviteCode,
		&i.InviteExpiresAt,
		&i.ActivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentsByParentID = `-- name: GetStudentsByParentID :many
SELECT id, parent_id, name, pin_hash, invite_code, invite_expires_at, activated_at, created_at FROM students
WHERE parent_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetStudentsByParentID(ctx context.Context, parentID pgtype.UUID) ([]Student, error) {
	rows, err := q.db.Query(ctx, getStudentsByParentID, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.PinHash,
			&i.InviteCode,
			&i.InviteExpiresAt,
			&i.ActivatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentNamesByParentID = `-- name: ListStudentNamesByParentID :many
SELECT id, name FROM students
WHERE parent_id = $1
ORDER BY name ASC
`

type ListStudentNamesByParentIDRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListStudentNamesByParentID(ctx context.Context, parentID pgtype.UUID) ([]ListStudentNamesByParentIDRow, error) {
	rows, err := q.db.Query(ctx, listStudentNamesByParentID, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentNamesByParentIDRow
	for rows.Next() {
		var i ListStudentNamesByParentIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
