// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subjects.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSubjectBySlug = `-- name: GetSubjectBySlug :one
SELECT id, name, slug, display_order FROM subjects WHERE slug = $1
`

type GetSubjectBySlugRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Slug         string      `json:"slug"`
	DisplayOrder int32       `json:"display_order"`
}

func (q *Queries) GetSubjectBySlug(ctx context.Context, slug string) (GetSubjectBySlugRow, error) {
	row := q.db.QueryRow(ctx, getSubjectBySlug, slug)
	var i GetSubjectBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DisplayOrder,
	)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, name, slug, display_order FROM subjects ORDER BY display_order
`

type ListSubjectsRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Slug         string      `json:"slug"`
	DisplayOrder int32       `json:"display_order"`
}

func (q *Queries) ListSubjects(ctx context.Context) ([]ListSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubjectsRow
	for rows.Next() {
		var i ListSubjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
