// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telegram.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTelegramLinkCode = `-- name: CreateTelegramLinkCode :one
INSERT INTO telegram_link_codes (code, student_id, expires_at)
VALUES ($1, $2, $3)
RETURNING code, student_id, expires_at, used_at
`

type CreateTelegramLinkCodeParams struct {
	Code      string             `json:"code"`
	StudentID pgtype.UUID        `json:"student_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTelegramLinkCode(ctx context.Context, arg CreateTelegramLinkCodeParams) (TelegramLinkCode, error) {
	row := q.db.QueryRow(ctx, createTelegramLinkCode, arg.Code, arg.StudentID, arg.ExpiresAt)
	var i TelegramLinkCode
	err := row.Scan(
		&i.Code,
		&i.StudentID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getTelegramLinkByTelegramUserID = `-- name: GetTelegramLinkByTelegramUserID :one
SELECT id, student_id, telegram_user_id, chat_id, linked_at FROM telegram_links WHERE telegram_user_id = $1
`

func (q *Queries) GetTelegramLinkByTelegramUserID(ctx context.Context, telegramUserID int64) (TelegramLink, error) {
	row := q.db.QueryRow(ctx, getTelegramLinkByTelegramUserID, telegramUserID)
	var i TelegramLink
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.TelegramUserID,
		&i.ChatID,
		&i.LinkedAt,
	)
	return i, err
}

const getTelegramLinkCode = `-- name: GetTelegramLinkCode :one
SELECT code, student_id, expires_at, used_at FROM telegram_link_codes WHERE code = $1
`

func (q *Queries) GetTelegramLinkCode(ctx context.Context, code string) (TelegramLinkCode, error) {
	row := q.db.QueryRow(ctx, getTelegramLinkCode, code)
	var i TelegramLinkCode
	err := row.Scan(
		&i.Code,
		&i.StudentID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getTelegramSession = `-- name: GetTelegramSession :one
SELECT chat_id, student_id, state, active_session_id, updated_at FROM telegram_sessions WHERE chat_id = $1
`

func (q *Queries) GetTelegramSession(ctx context.Context, chatID int64) (TelegramSession, error) {
	row := q.db.QueryRow(ctx, getTelegramSession, chatID)
	var i TelegramSession
	err := row.Scan(
		&i.ChatID,
		&i.StudentID,
		&i.State,
		&i.ActiveSessionID,
		&i.UpdatedAt,
	)
	return i, err
}

const listTelegramLinks = `-- name: ListTelegramLinks :many
SELECT id, student_id, telegram_user_id, chat_id, linked_at FROM telegram_links
`

func (q *Queries) ListTelegramLinks(ctx context.Context) ([]TelegramLink, error) {
	rows, err := q.db.Query(ctx, listTelegramLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelegramLink
	for rows.Next() {
		var i TelegramLink
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.TelegramUserID,
			&i.ChatID,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTelegramLinkCodeUsed = `-- name: MarkTelegramLinkCodeUsed :exec
UPDATE telegram_link_codes SET used_at = NOW() WHERE code = $1
`

func (q *Queries) MarkTelegramLinkCodeUsed(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, markTelegramLinkCodeUsed, code)
	return err
}

const tryInsertTelegramReminder = `-- name: TryInsertTelegramReminder :execrows
INSERT INTO telegram_reminders (student_id, sent_on)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type TryInsertTelegramReminderParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	SentOn    pgtype.Date `json:"sent_on"`
}

func (q *Queries) TryInsertTelegramReminder(ctx context.Context, arg TryInsertTelegramReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryInsertTelegramReminder, arg.StudentID, arg.SentOn)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertTelegramLink = `-- name: UpsertTelegramLink :one
INSERT INTO telegram_links (student_id, telegram_user_id, chat_id)
VALUES ($1, $2, $3)
ON CONFLICT (student_id)
DO UPDATE SET telegram_user_id = $2, chat_id = $3, linked_at = NOW()
RETURNING id, student_id, telegram_user_id, chat_id, linked_at
`

type UpsertTelegramLinkParams struct {
	StudentID      pgtype.UUID `json:"student_id"`
	TelegramUserID int64       `json:"telegram_user_id"`
	ChatID         int64       `json:"chat_id"`
}

func (q *Queries) UpsertTelegramLink(ctx context.Context, arg UpsertTelegramLinkParams) (TelegramLink, error) {
	row := q.db.QueryRow(ctx, upsertTelegramLink, arg.StudentID, arg.TelegramUserID, arg.ChatID)
	var i TelegramLink
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.TelegramUserID,
		&i.ChatID,
		&i.LinkedAt,
	)
	return i, err
}

const upsertTelegramSession = `-- name: UpsertTelegramSession :one
INSERT INTO telegram_sessions (chat_id, student_id, state, active_session_id, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (chat_id)
DO UPDATE SET student_id = $2, state = $3, active_session_id = $4, updated_at = NOW()
RETURNING chat_id, student_id, state, active_session_id, updated_at
`

type UpsertTelegramSessionParams struct {
	ChatID          int64       `json:"chat_id"`
	StudentID       pgtype.UUID `json:"student_id"`
	State           string      `json:"state"`
	ActiveSessionID pgtype.UUID `json:"active_session_id"`
}

func (q *Queries) UpsertTelegramSession(ctx context.Context, arg UpsertTelegramSessionParams) (TelegramSession, error) {
	row := q.db.QueryRow(ctx, upsertTelegramSession,
		arg.ChatID,
		arg.StudentID,
		arg.State,
		arg.ActiveSessionID,
	)
	var i TelegramSession
	err := row.Scan(
		&i.ChatID,
		&i.StudentID,
		&i.State,
		&i.ActiveSessionID,
		&i.UpdatedAt,
	)
	return i, err
}
