// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topics.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTopicBySlug = `-- name: GetTopicBySlug :one
SELECT t.id, t.subject_id, t.name, t.slug, t.display_order FROM topics t JOIN subjects s ON t.subject_id = s.id WHERE s.slug = $1 AND t.slug = $2
`

type GetTopicBySlugParams struct {
	SubjectSlug string `json:"subject_slug"`
	TopicSlug   string `json:"topic_slug"`
}

type GetTopicBySlugRow struct {
	ID           pgtype.UUID `json:"id"`
	SubjectID    pgtype.UUID `json:"subject_id"`
	Name         string      `json:"name"`
	Slug         string      `json:"slug"`
	DisplayOrder int32       `json:"display_order"`
}

func (q *Queries) GetTopicBySlug(ctx context.Context, arg GetTopicBySlugParams) (GetTopicBySlugRow, error) {
	row := q.db.QueryRow(ctx, getTopicBySlug, arg.SubjectSlug, arg.TopicSlug)
	var i GetTopicBySlugRow
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Name,
		&i.Slug,
		&i.DisplayOrder,
	)
	return i, err
}

const listTopicsBySubjectID = `-- name: ListTopicsBySubjectID :many
SELECT id, subject_id, name, slug, display_order FROM topics WHERE subject_id = $1 ORDER BY display_order
`

type ListTopicsBySubjectIDRow struct {
	ID           pgtype.UUID `json:"id"`
	SubjectID    pgtype.UUID `json:"subject_id"`
	Name         string      `json:"name"`
	Slug         string      `json:"slug"`
	DisplayOrder int32       `json:"display_order"`
}

func (q *Queries) ListTopicsBySubjectID(ctx context.Context, subjectID pgtype.UUID) ([]ListTopicsBySubjectIDRow, error) {
	rows, err := q.db.Query(ctx, listTopicsBySubjectID, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopicsBySubjectIDRow
	for rows.Next() {
		var i ListTopicsBySubjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Name,
			&i.Slug,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
